### ISSUE TITLE
Editar perfil

### ISSUE THREAD

**Issue by btrcardoso** [btrcardoso/yarural#10]
- [x] Fazer formulario para editar perfil
- [x] Armazenamento dos dados editados no banco
- [x] Consertar mensagens de validação para inputs vazios
- [x] Retornar valores já editados dos inputs quando o usuário errar na validação

**Comment by SullyvanMoura** [comment]
Validator do username tem problemas

**Comment by SullyvanMoura** [comment]
O username não pode conter letras maiúsculas. Talvez deva-se usar um regex ou um custom validator para resolver este problema

**Comment by btrcardoso** [comment]
> Validator do username tem problemas
> 
> * O username nao deve ter sinais como <,>,/...
> * Aconselha a usar o rules.escape() para resolver este problema

Resolvido com o rules.alphaNum(). Apenas caracteres alfa-numéricos são permitidos. Também foi adicionada uma permissão para underline e hífen.
