### ISSUE TITLE
Incluir sistema de pontos e ranking

### ISSUE THREAD

**Issue by SullyvanMoura** [btrcardoso/yarural#37]
- [x] Definir tabela de pontos
- [x] Colocar pontos no perfil
- [x] Ranking de pontos

**Comment by SullyvanMoura** [comment]
- [x] Pontos para perguntas
- [x] Pontos para respostas
- [x] Pontos para votos

**Comment by btrcardoso** [comment]
Consertar:
- [ ] Se o usuário tiver 0 pontos e receber dislike ou apagar resposta, a pontuação não é alterada.
- [ ] A colocação no perfil do usuário na aba de respostas está como undefined.
